package com.example.grocery_inventory.util;

import io.github.cdimascio.dotenv.Dotenv;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/*
Supabase SQL setup script:

-- categories table
CREATE TABLE IF NOT EXISTS categories (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

-- products table
CREATE TABLE IF NOT EXISTS products (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode     VARCHAR(50)    NOT NULL,
    name        VARCHAR(150)   NOT NULL,
    category_id INT            NOT NULL,
    price       NUMERIC(10,2)  NOT NULL,
    stock       INT            NOT NULL DEFAULT 0,
    unit        VARCHAR(30)    NOT NULL DEFAULT 'pcs',
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_products_barcode UNIQUE (barcode),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- auto-update updated_at trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- users table
CREATE TABLE IF NOT EXISTS users (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50) NOT NULL,
    password_hash TEXT        NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'VIEWER',
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'OPERATOR', 'VIEWER')),
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- activity_log table
CREATE TABLE IF NOT EXISTS activity_log (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(50)  NOT NULL,
    entity       VARCHAR(50)  NOT NULL,
    description  TEXT         NOT NULL,
    performed_by VARCHAR(50)  NOT NULL DEFAULT 'system',
    performed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- seed categories
INSERT INTO categories (name) VALUES
('Beverages'),('Dairy'),('Bakery'),('Meat & Seafood'),
('Fruits & Vegetables'),('Snacks'),('Canned Goods'),('Condiments');

-- seed admin account (password: adminpassword)
INSERT INTO users (username, password_hash, role) VALUES (
    'admin123',
    '$2a$12$2cHOnE.TGDRHpPpsusNXBuhGbVO5FlEjvdAIt1XfD8E7jFXSidthO',
    'ADMIN'
);

-- seed sample products
INSERT INTO products (barcode, name, category_id, price, stock, unit) VALUES
('4800016350015','Coca-Cola 1.5L',    1,75.00,50,'bottle'),
('4800016350022','Nestea Iced Tea 1L',1,45.00,80,'bottle'),
('4800159170019','Bear Brand Milk 1L',2,95.00,30,'carton'),
('4807772009999','Gardenia White Bread',3,65.00,25,'loaf'),
('4800020800011','Century Tuna 180g', 7,42.00,100,'can');
*/
public final class DatabaseUtil {
    private static final Dotenv DOTENV = loadDotenv();
    private static final String URL = DOTENV.get("DB_URL");
    private static final String USER = DOTENV.get("DB_USER");
    private static final String PASSWORD = DOTENV.get("DB_PASSWORD");

    private DatabaseUtil() {
    }

    public static Connection getConnection() throws SQLException {
        if (isBlank(URL) || isBlank(USER) || isBlank(PASSWORD)) {
            throw new SQLException("Database credentials are missing. Check DB_URL, DB_USER, and DB_PASSWORD in .env.");
        }
        loadPostgresDriver();
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    private static void loadPostgresDriver() throws SQLException {
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException ex) {
            throw new SQLException("PostgreSQL JDBC driver is not available on the module path.", ex);
        }
    }

    private static Dotenv loadDotenv() {
        String directory = Files.exists(Path.of(".env")) ? "." : "grocery_inventory";
        return Dotenv.configure()
                .directory(directory)
                .load();
    }

    private static boolean isBlank(String value) {
        return value == null || value.isBlank();
    }
}
