-- categories table
CREATE TABLE IF NOT EXISTS categories (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

-- products table
CREATE TABLE IF NOT EXISTS products (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barcode     VARCHAR(50)    NOT NULL,
    name        VARCHAR(150)   NOT NULL,
    category_id INT            NOT NULL,
    price       NUMERIC(10,2)  NOT NULL,
    stock       INT            NOT NULL DEFAULT 0,
    unit        VARCHAR(30)    NOT NULL DEFAULT 'pcs',
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_products_barcode UNIQUE (barcode),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- auto-update updated_at trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = CURRENT_TIMESTAMP; RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;

CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- users table
CREATE TABLE IF NOT EXISTS users (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50) NOT NULL,
    password_hash TEXT        NOT NULL,
    role          VARCHAR(20) NOT NULL DEFAULT 'VIEWER',
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'OPERATOR', 'VIEWER')),
    CONSTRAINT uk_users_username UNIQUE (username)
);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'VIEWER';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_users_role'
    ) THEN
        ALTER TABLE users
        ADD CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'OPERATOR', 'VIEWER'));
    END IF;
END;
$$;

-- activity_log table
CREATE TABLE IF NOT EXISTS activity_log (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(50)  NOT NULL,
    entity       VARCHAR(50)  NOT NULL,
    description  TEXT         NOT NULL,
    performed_by VARCHAR(50)  NOT NULL DEFAULT 'system',
    performed_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- seed categories
INSERT INTO categories (name) VALUES
('Beverages'),('Dairy'),('Bakery'),('Meat & Seafood'),
('Fruits & Vegetables'),('Snacks'),('Canned Goods'),('Condiments')
ON CONFLICT (name) DO NOTHING;

-- seed admin account (password: adminpassword)
INSERT INTO users (username, password_hash, role) VALUES (
    'admin123',
    '$2a$12$2cHOnE.TGDRHpPpsusNXBuhGbVO5FlEjvdAIt1XfD8E7jFXSidthO',
    'ADMIN'
)
ON CONFLICT (username) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    role = 'ADMIN';

-- seed operator account (password: Employeepassword)
INSERT INTO users (username, password_hash, role) VALUES (
    'Employee',
    '$2a$12$GL4GFBFnbA4wOePBIE1MVeqvMMNr.uX8aS4LfBrJw1Wl3rQe0pNGG',
    'OPERATOR'
)
ON CONFLICT (username) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    role = 'OPERATOR';

-- seed viewer account (password: Viewerpassword)
INSERT INTO users (username, password_hash, role) VALUES (
    'Vieweronly',
    '$2a$12$4okePN7C/Y6yfEjw6OGWweD80MRoxX20xB6BjA9iT/DZu6Wl1BFyu',
    'VIEWER'
)
ON CONFLICT (username) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    role = 'VIEWER';

-- seed sample products
INSERT INTO products (barcode, name, category_id, price, stock, unit) VALUES
('4800016350015','Coca-Cola 1.5L',    1,75.00,50,'bottle'),
('4800016350022','Nestea Iced Tea 1L',1,45.00,80,'bottle'),
('4800159170019','Bear Brand Milk 1L',2,95.00,30,'carton'),
('4807772009999','Gardenia White Bread',3,65.00,25,'loaf'),
('4800020800011','Century Tuna 180g', 7,42.00,100,'can')
ON CONFLICT (barcode) DO NOTHING;
